### ISSUE TITLE
Query Error: INSERT INTO fusionu7I34_cookie_control

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1061]
have try to install older infusion "cookie control" and get this: 
Notice: this infusion works 100% until yesterday on my server with PHP F 9

Query Error: INSERT INTO fusionu7I34_cookie_control (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc)
Stack Trace: #0 /var/www/vhosts/aliencollectors.com/httpdocs/site/includes/classes/PHPFusion/Database/Driver/PDOMySQL.php(64): PDO->prepare('INSERT INTO fus...') #1 /var/www/vhosts/aliencollectors.com/httpdocs/site/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.php(300): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array) #2 /var/www/vhosts/aliencollectors.com/httpdocs/site/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array) #3 /var/www/vhosts/aliencollectors.com/httpdocs/site/administration/infusions.php(303): dbquery('INSERT INTO fus...') #4 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by meangczac** [comment]
Please show - Paste the cookie control's infusion.php here.

**Comment by UnrealCatze** [comment]
```
<?php
/*-------------------------------------------------------+
| PHP-Fusion Content Management System
| Copyright © 2002 - 2013 Nick Jones
| http://www.php-fusion.co.uk/
+--------------------------------------------------------+
| Filename: infusion.php
| Author: Nick Jones
| Author: PHP-Fusion Mods UK
| Developers: Craig
| Sites: http://www.phpfusionmods.co.uk
+--------------------------------------------------------+
| This program is released as free software under the
| Affero GPL license. You can redistribute it and/or
| modify it under the terms of this license which you
| can read by viewing the included agpl.txt or online
| at www.gnu.org/licenses/agpl.html. Removal of this
| copyright header is strictly prohibited without
| written permission from the original author(s).
+--------------------------------------------------------*/
if (!defined("IN_FUSION")) { die("Access Denied"); }
include INFUSIONS."cookie_control/infusion_db.php";
if (file_exists(INFUSIONS."cookie_control/locale/".$settings['locale'].".php")) {
        include INFUSIONS."cookie_control/locale/".$settings['locale'].".php";
    } else {
        include INFUSIONS."cookie_control/locale/English.php";
    }


// Infusion general information
$inf_title = $locale['ecdp_001'];
$inf_description = $locale['ecdp_002'];
$inf_version = "2.00";
$inf_developer = "PHP-Fusion Mods UK";
$inf_email = "admin@phpfusionmods.co.uk";
$inf_weburl = "http://www.phpfusionmods.co.uk";

$inf_folder = "cookie_control";

$inf_newtable[1] = DB_COOKIE_CONTROL." (
cookie_id MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
cookie_cookie VARCHAR(45) NOT NULL DEFAULT '',
cookie_default VARCHAR(8) NOT NULL DEFAULT '',
cookie_usage VARCHAR(45) NOT NULL DEFAULT '',
cookie_desc TEXT NOT NULL,
PRIMARY KEY (cookie_id)
) ENGINE=MyISAM;";

$inf_newtable[2] = DB_COOKIE_SETTINGS." (
cc_enable TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL,
cc_text TEXT NOT NULL,
cc_time VARCHAR(3) NOT NULL DEFAULT '',
cc_position TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL,
cc_bgcolour VARCHAR(6) NOT NULL DEFAULT '',
cc_border VARCHAR(6) NOT NULL DEFAULT '',
cc_accept VARCHAR(6) NOT NULL DEFAULT '',
cc_accept_hover VARCHAR(6) NOT NULL DEFAULT '',
cc_accept_border VARCHAR(6) NOT NULL DEFAULT '',
cc_accept_border_hover VARCHAR(6) NOT NULL DEFAULT '',
cc_accept_text VARCHAR(6) NOT NULL DEFAULT '',
cc_accept_text_hover VARCHAR(6) NOT NULL DEFAULT '',
PRIMARY KEY (cc_enable)
) ENGINE=MyISAM;";

$inf_insertdbrow[1] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc)";

$inf_insertdbrow[2] = DB_COOKIE_SETTINGS." (cc_enable,  cc_text,  cc_time, cc_position, cc_bgcolour, cc_border, cc_accept, cc_accept_hover, cc_accept_border, cc_accept_border_hover, cc_accept_text, cc_accept_text_hover) VALUES ('1', '".$locale['ecdp_038']."', '365', '1', '999999', 'DDDDDD', 'A3A3A3', 'A9A9A9', 'B7B5B5', 'C9C9C9', 'FFFFFF', 'FFFFFF')";

$inf_insertdbrow[3] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc)";

$inf_insertdbrow[4] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc) VALUES ('1', '', '4', '8', '".$locale['ecdp_075']."')";

$inf_insertdbrow[5] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc) VALUES ('2', '', '1', '8', '".$locale['ecdp_020']."')";

$inf_insertdbrow[6] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc) VALUES ('3', '', '2', '8', '".$locale['ecdp_021']."')";

$inf_insertdbrow[7] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc) VALUES ('4', '', '3', '8', '".$locale['ecdp_074']."')";

$inf_insertdbrow[8] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc) VALUES ('5', '', '5', '8', '".$locale['ecdp_019']."')";

$inf_insertdbrow[9] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc) VALUES ('6', '', '6', '1', '".$locale['ecdp_076']."')";

$inf_droptable[1] = DB_COOKIE_CONTROL;

$inf_droptable[2] = DB_COOKIE_SETTINGS;

$inf_adminpanel[1] = array(
    "title" => $locale['ecdp_001'],
    "image" => "",
    "panel" => "cookie_control_admin.php",
    "rights" => "CCP"
);


?>
```

**Comment by meangczac** [comment]
Inf_insertdbrow [1] is wrong. It is so obvious. Where is the values??? Are you sure that is the file?

**Comment by UnrealCatze** [comment]
it works .. this error comes only when i infuse it. When i clear the error memory i get no error anymomre

and it really the cookie control's infusion.php ... you asked for this :)

**Comment by UnrealCatze** [comment]
yea guess it mus be delete not more -- line 3 it the same :O

**Comment by meangczac** [comment]
No.....

This one has no value to insert.. If no value to insert, just remove this.... 

```
$inf_insertdbrow[1] = DB_COOKIE_CONTROL." (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc)";
```

Because your error is...
**Query Error:** INSERT INTO **fusionu7I34_cookie_control (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc)**
