### ISSUE TITLE
Installation - News Infusion error

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1084]
Notice: Query Error: ALTER TABLE fusion241T1_news_cats ADD news_cat_visibility TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' AFTER news_cat_image<br/>Stack Trace: #0 F:\xampp\htdocs\pf92\includes\classes\PHPFusion\Database\Driver\PDOMySQL.php(68): PDOStatement->execute() #1 F:\xampp\htdocs\pf92\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.php(303): PHPFusion\Database\Driver\PDOMySQL->_query('ALTER TABLE fus...', Array) #2 F:\xampp\htdocs\pf92\includes\db_handlers\all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('ALTER TABLE fus...', Array) #3 F:\xampp\htdocs\pf92\includes\classes\PHPFusion\Installer\Infusion.core.inc(525): dbquery('ALTER TABLE fus...') #4 F:\xampp\htdocs\pf92\includes\classes\PHPFusion\Installer\Infusion.core.inc(147): PHPFusion\Installer\Infusion_Core->altertable_infuse(Array) #5 F:\xampp\htdocs\pf92\includes\classes\PHPFusion\Installer\Install.core.inc(1205): PHPFusion\Installer\Infusion_Core->infuse('news') #6 F:\xampp\htdocs\pf92\includes\classes\PHPFusion in F:\xampp\htdocs\pf92\includes\classes\PHPFusion\Database\Driver\PDOMySQL.php on line 72

**Comment by RobiNN1** [comment]
solved
