### ISSUE TITLE
default new installation throws exception on profile

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1143]
"Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /home/nextphpf/public_html/RC7/includes/core_functions_include.php:1384 Stack trace: #0 /home/nextphpf/public_html/RC7/includes/core_functions_include.php(1384): DateTimeZone->__construct('') #1 /home/nextphpf/public_html/RC7/includes/classes/PHPFusion/UserFields.inc(562): showdate('longdate', 1478810002) #2 /home/nextphpf/public_html/RC7/profile.php(66): PHPFusion\UserFields->get_profile_output() #3 {main} thrown in /home/nextphpf/public_html/RC7/includes/core_functions_include.php on line 1384"

![untitled-2](https://cloud.githubusercontent.com/assets/4210004/20193757/bfa4be36-a78f-11e6-9b3f-4f909a91563a.png)

**Comment by JoakimFalk** [comment]
Not only profile, it was just one of them areas not loading at all.
It is the server DateTimeZones that are not updated (On next anyway) in a new installation.
Once manually inserted everything seems ok. But the glitch need a fix.
