### ISSUE TITLE
Sql Error on upgraded articles

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1443]
Query Error: SELECT * FROM demos6ef8L_article_cats WHERE WHERE article_cat_language='English' AND article_cat_id=:cat_id AND article_cat_status=:status AND 1 = 1 
Stack Trace: 
#0 /home/pfdemos/public_html/v7_Default/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('\n SE...') 
#1 /home/pfdemos/public_html/v7_Default/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('\n SE...', Array) 
#2 /home/pfdemos/public_html/v7_Default/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('\n SE...', Array) 
#3 /home/pfdemos/public_html/v7_Default/infusions/articles/classes/articles/articles.php(351): dbquery('\n SE...', Array) 
#4 /home/pfdemos/public_html/v7_Default/infusions/articles/classes/articles/articles_view.php(38): PHPFusion\Articles\Articles->set_ArticlesCatInfo('1') 
#5 /home/pfdemos/public_html/v7_Default/infusions/articles/articles.php(27): PHPFusion\Articles\ArticlesView->display_articles() 
#6 {main}
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE article_cat_language='English' AND article_cat_id=? AND art' at line 3

**Comment by JoakimFalk** [comment]
Confirmed Fix.
