### ISSUE TITLE
Upgrade error for Forums in the latest github version

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1583]
> Everything was fine till I tried to upgrade the forums, then got this:
> This item cannot be infused
> 

````
Notice: Query Error: INSERT INTO fusion3q966_settings_inf (settings_name, settings_value, settings_inf) VALUES ('upvote_points', '2', 'forum')
Stack Trace: #0 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(67): PDOStatement->execute() #1 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array) #2 /home/xxxx/public_html/frackemall/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array) #3 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(634): dbquery('INSERT INTO fus...') #4 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(130): PHPFusion\Installer\Infusion_Core->insertdbrow_infuse(Array) #5 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Steps/InfusionsSetu in /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc on line 71

Notice: Query Error: INSERT INTO fusion3q966_settings_inf (settings_name, settings_value, settings_inf) VALUES ('downvote_points', '1', 'forum')
Stack Trace: #0 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(67): PDOStatement->execute() #1 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array) #2 /home/xxxx/public_html/frackemall/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array) #3 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(634): dbquery('INSERT INTO fus...') #4 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(130): PHPFusion\Installer\Infusion_Core->insertdbrow_infuse(Array) #5 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Steps/InfusionsSe in /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc on line 71

Notice: Query Error: INSERT INTO fusion3q966_settings_inf (settings_name, settings_value, settings_inf) VALUES ('answering_points', '15', 'forum')
Stack Trace: #0 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(67): PDOStatement->execute() #1 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array) #2 /home/xxxx/public_html/frackemall/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array) #3 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(634): dbquery('INSERT INTO fus...') #4 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(130): PHPFusion\Installer\Infusion_Core->insertdbrow_infuse(Array) #5 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Steps/Infusions in /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc on line 71

Notice: Query Error: INSERT INTO fusion3q966_settings_inf (settings_name, settings_value, settings_inf) VALUES ('points_to_upvote', '100', 'forum')
Stack Trace: #0 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(67): PDOStatement->execute() #1 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array) #2 /home/xxxx/public_html/frackemall/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array) #3 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(634): dbquery('INSERT INTO fus...') #4 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(130): PHPFusion\Installer\Infusion_Core->insertdbrow_infuse(Array) #5 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Steps/Infusion in /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc on line 71

Notice: Query Error: INSERT INTO fusion3q966_settings_inf (settings_name, settings_value, settings_inf) VALUES ('points_to_downvote', '100', 'forum')
Stack Trace: #0 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(67): PDOStatement->execute() #1 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array) #2 /home/xxxx/public_html/frackemall/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array) #3 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(634): dbquery('INSERT INTO fus...') #4 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Infusion.core.inc(130): PHPFusion\Installer\Infusion_Core->insertdbrow_infuse(Array) #5 /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Installer/Steps/Infusi in /home/xxxx/public_html/frackemall/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc on line 71
PHP-Fusion InstallPHP-Fusion
````
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38460&pid=202145#post_202145

**Comment by meangczac** [comment]
Fixed https://github.com/php-fusion/PHP-Fusion/commit/b1188dc9b1e39d02cb477a5d744a49b0bc378a29
