### ISSUE TITLE
Sub-Header Links error

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1816]
Make sense to anyone?

```
Query Error: SELECT d.*, dc.*, tu.user_id, tu.user_name, tu.user_status, tu.user_avatar , tu.user_level, tu.user_joined, IF(SUM(tr.rating_vote)>0, SUM(tr.rating_vote), 0) AS sum_rating, COUNT(tr.rating_item_id) AS count_votes, MAX(d.download_datestamp) as last_updated FROM fusion9Im64_downloads d INNER JOIN fusion9Im64_download_cats dc ON d.download_cat=dc.download_cat_id LEFT JOIN fusion9Im64_users tu ON d.download_user=tu.user_id LEFT JOIN fusion9Im64_ratings tr ON tr.rating_item_id = d.download_id AND tr.rating_type='D' WHERE download_cat_language='English' AND download_visibility = 0 AND download_cat = '6' GROUP BY d.download_id ORDER BY count_comment DESC LIMIT 0,15
Stack Trace: #0 /home/mypleasu/public_html/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('SELECT d.*, dc....') #1 /home/mypleasu/public_html/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(303): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT d.*, dc....', Array) #2 /home/mypleasu/public_html/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT d.*, dc....', Array) #3 /home/mypleasu/public_html/infusions/downloads/downloads.php(249): dbquery('SELECT d.*, dc....') #4 {main}
Error Nature: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count_comment' in 'order clause'
```

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38572&pid=202666#post_202666

**Comment by RobiNN1** [comment]
It's a download comments issue, not sub-links.
I tested all pages and comments and I don't get this error.
